// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1_rxQHyaW_WdryBJ4n_PhicXQakoumn4',
    appId: '1:479290647178:web:08c4d4d0d819df21214373',
    messagingSenderId: '479290647178',
    projectId: 'oh-yeah-official',
    authDomain: 'oh-yeah-official.firebaseapp.com',
    storageBucket: 'oh-yeah-official.firebasestorage.app',
    measurementId: 'G-P4BGYSDJWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRTvMnWm5kJc6Fwvmjc54x7WJnecmObw4',
    appId: '1:479290647178:android:7b751d753e49010a214373',
    messagingSenderId: '479290647178',
    projectId: 'oh-yeah-official',
    storageBucket: 'oh-yeah-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3Q_nSJQ_spgWhkGqVpmc8faz7oWyzcE',
    appId: '1:479290647178:ios:3ca8fec28c285274214373',
    messagingSenderId: '479290647178',
    projectId: 'oh-yeah-official',
    storageBucket: 'oh-yeah-official.firebasestorage.app',
    iosBundleId: 'com.ryozo.ohyeah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3Q_nSJQ_spgWhkGqVpmc8faz7oWyzcE',
    appId: '1:479290647178:ios:197bb73f787da8b1214373',
    messagingSenderId: '479290647178',
    projectId: 'oh-yeah-official',
    storageBucket: 'oh-yeah-official.firebasestorage.app',
    iosBundleId: 'com.example.ohYeahNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1_rxQHyaW_WdryBJ4n_PhicXQakoumn4',
    appId: '1:479290647178:web:b4868d7c88abcf48214373',
    messagingSenderId: '479290647178',
    projectId: 'oh-yeah-official',
    authDomain: 'oh-yeah-official.firebaseapp.com',
    storageBucket: 'oh-yeah-official.firebasestorage.app',
    measurementId: 'G-BZ7JLJB5BL',
  );

}