// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVw1EW3vg3YWI_dMGQl4OANajz3p9O9Q',
    appId: '1:642657130095:web:a0daf83c3a80c4311c9f9a',
    messagingSenderId: '642657130095',
    projectId: 'oh-yeah-9fdc6',
    authDomain: 'oh-yeah-9fdc6.firebaseapp.com',
    storageBucket: 'oh-yeah-9fdc6.firebasestorage.app',
    measurementId: 'G-0SHHD0BPWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxooaCGo3WC0Xq96fRcgIw34A9ewewCA',
    appId: '1:642657130095:android:2df826001b1c10f51c9f9a',
    messagingSenderId: '642657130095',
    projectId: 'oh-yeah-9fdc6',
    storageBucket: 'oh-yeah-9fdc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVJEcg-S4giz-1H6OwPoTu8RpGxtTXaPI',
    appId: '1:642657130095:ios:c293fa87396464c61c9f9a',
    messagingSenderId: '642657130095',
    projectId: 'oh-yeah-9fdc6',
    storageBucket: 'oh-yeah-9fdc6.firebasestorage.app',
    iosBundleId: 'com.ryozo.ohyeah.barapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVJEcg-S4giz-1H6OwPoTu8RpGxtTXaPI',
    appId: '1:642657130095:ios:bf92c2ec330c12991c9f9a',
    messagingSenderId: '642657130095',
    projectId: 'oh-yeah-9fdc6',
    storageBucket: 'oh-yeah-9fdc6.firebasestorage.app',
    iosBundleId: 'com.example.barAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaVw1EW3vg3YWI_dMGQl4OANajz3p9O9Q',
    appId: '1:642657130095:web:2118a92adb2f9e251c9f9a',
    messagingSenderId: '642657130095',
    projectId: 'oh-yeah-9fdc6',
    authDomain: 'oh-yeah-9fdc6.firebaseapp.com',
    storageBucket: 'oh-yeah-9fdc6.firebasestorage.app',
    measurementId: 'G-2GS13S6GE5',
  );
}
